<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="CallThisSingleTimeEachCycle" Id="{17bc738b-5835-46a1-928e-ac82fd18c60a}" SpecialFunc="None">
    <Declaration><![CDATA[
FUNCTION CallThisSingleTimeEachCycle : BOOL
]]></Declaration>
    <Implementation>
      <ST><![CDATA[
TaskHeartbeat(update := TRUE);
]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>