<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.11">
  <POU Name="Signal" Id="{4e871047-b7ef-4985-9527-6f58bffc7244}" SpecialFunc="None">
    <Declaration><![CDATA[
FUNCTION Signal : REFERENCE TO SignalBundle
VAR_INPUT
	symbol			: REFERENCE TO BOOL;
END_VAR
VAR
END_VAR
VAR_STAT
	provider		: SignalProvider;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[
IF (__ISVALIDREF(symbol)) THEN
	Signal REF= provider.Get(symbol);
ELSE
	provider.Call();
END_IF
]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>