<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.11">
  <POU Name="HashMap" Id="{034d47c3-248f-4e5a-a7e3-eda5f7ee95dc}" SpecialFunc="None">
    <Declaration><![CDATA[
FUNCTION_BLOCK HashMap IMPLEMENTS Map
VAR_INPUT
END_VAR
VAR_OUTPUT
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>